# Generated by Django 3.2.12 on 2022-02-01 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
