# Generated by Django 3.2.12 on 2022-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.CharField(blank=True, choices=[('True', 'Completed'), ('False', 'To be Completed')], default=False, max_length=20, null=True),
        ),
    ]
